const CONCEPTS_DATA = [
  {
    slug: 'programming-basics',
    name: 'Programming Basics',
    order: 1,
    description: 'Foundations of JVM, compilation process, bytecode, main method anatomy, and basic I/O in Java.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 70,
    difficultyRange: { min: 1, max: 3 },
    prereqSlugs: [],
  },
  {
    slug: 'variables-datatypes',
    name: 'Variables & Data Types',
    order: 2,
    description: 'Primitive types, non-primitive reference types, variable scopes, type casting, and memory allocation.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 70,
    difficultyRange: { min: 1, max: 4 },
    prereqSlugs: ['programming-basics'],
  },
  {
    slug: 'operators',
    name: 'Operators',
    order: 3,
    description: 'Arithmetic, relational, logical, bitwise, assignment, and ternary operators with precedence rules.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 70,
    difficultyRange: { min: 1, max: 4 },
    prereqSlugs: ['variables-datatypes'],
  },
  {
    slug: 'conditionals',
    name: 'Conditional Statements',
    order: 4,
    description: 'if-else branches, nested decisions, switch-case expressions, pattern matching, and short-circuit evaluation.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 70,
    difficultyRange: { min: 1, max: 4 },
    prereqSlugs: ['operators'],
  },
  {
    slug: 'loops',
    name: 'Loops',
    order: 5,
    description: 'for, while, do-while iteration, loop invariants, break/continue flow control, and nested loop performance.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 75,
    difficultyRange: { min: 1, max: 5 },
    prereqSlugs: ['conditionals'],
  },
  {
    slug: 'functions',
    name: 'Functions / Methods',
    order: 6,
    description: 'Method signatures, parameter passing by value, return types, method overloading, and recursion.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 75,
    difficultyRange: { min: 2, max: 5 },
    prereqSlugs: ['loops'],
  },
  {
    slug: 'oop-basics',
    name: 'OOP Basics',
    order: 7,
    description: 'Classes, objects, constructors, this keyword, static vs instance context, and object lifecycle in heap memory.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 75,
    difficultyRange: { min: 2, max: 5 },
    prereqSlugs: ['functions'],
  },
  {
    slug: 'encapsulation',
    name: 'Encapsulation',
    order: 8,
    description: 'Access modifiers (private, protected, public, package-private), data hiding, getters/setters, and immutable objects.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 70,
    difficultyRange: { min: 2, max: 4 },
    prereqSlugs: ['oop-basics'],
  },
  {
    slug: 'inheritance',
    name: 'Inheritance',
    order: 9,
    description: 'extends keyword, super keyword, method overriding, polymorphism, IS-A relationships, and final keyword.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 75,
    difficultyRange: { min: 2, max: 5 },
    prereqSlugs: ['oop-basics'],
  },
  {
    slug: 'collections',
    name: 'Collections',
    order: 10,
    description: 'List, Set, Map hierarchies, ArrayList vs LinkedList, HashMap internals, iterators, and generics.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 75,
    difficultyRange: { min: 2, max: 5 },
    prereqSlugs: ['encapsulation', 'inheritance'],
  },
  {
    slug: 'exception-handling',
    name: 'Exception Handling',
    order: 11,
    description: 'Checked vs unchecked exceptions, try-catch-finally, try-with-resources, throw/throws, and custom exceptions.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 75,
    difficultyRange: { min: 2, max: 5 },
    prereqSlugs: ['programming-basics', 'oop-basics'],
  },
  {
    slug: 'problem-solving',
    name: 'Problem Solving',
    order: 12,
    description: 'Synthesizing algorithms, complex flow analysis, data structure selection, edge-case mitigation, and transfer tasks.',
    category: 'Java Programming Fundamentals',
    requiredMastery: 80,
    difficultyRange: { min: 3, max: 5 },
    prereqSlugs: ['collections', 'functions', 'oop-basics'],
  },
];

module.exports = { CONCEPTS_DATA };
