import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatDate(dateString?: string): string {
  if (!dateString) return "N/A";
  try {
    return new Date(dateString).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return dateString;
  }
}

export function getScoreColor(score: number): string {
  if (score >= 80) return "text-emerald-400 border-emerald-500/40 bg-emerald-500/10";
  if (score >= 60) return "text-amber-400 border-amber-500/40 bg-amber-500/10";
  return "text-rose-400 border-rose-500/40 bg-rose-500/10";
}

export function getSourceBadgeInfo(sourceType?: string): {
  label: string;
  badgeClass: string;
  description: string;
} {
  switch (sourceType) {
    case "database_question":
      return {
        label: "🏢 Database Question",
        badgeClass: "bg-blue-500/20 text-blue-300 border-blue-500/40",
        description: "Grounded directly in verified collected interview questions for this company.",
      };
    case "pattern_derived":
      return {
        label: "🧬 Pattern-Derived",
        badgeClass: "bg-purple-500/20 text-purple-300 border-purple-500/40",
        description: "Generated by Gemini AI matching verified interview patterns of this company.",
      };
    case "generic_role_based":
    default:
      return {
        label: "🎯 Role-Based",
        badgeClass: "bg-slate-500/20 text-slate-300 border-slate-500/40",
        description: "Generated from general industry interview patterns for your selected role.",
      };
  }
}
